version: '3.7'

services:

  web:
    image: elephantbox/elephantbox:jammy-p82n19-latest
    command: run-services nginx,php-fpm
    environment:
      APP_NAME: demo
      APP_ENV: local
      ENTRYPOINT_SCRIPT: /app/demo/.entryscript.sh
      PHP_IDE_CONFIG: serverName=localhost
    working_dir: /app/demo
    ports:
      - "8000:80"
    volumes:
      - .:/app
